services:
  tor:
    image: dperson/torproxy
    container_name: tor
    restart: unless-stopped
    ports:
      - "9050:9050"
    environment:
      - LOCATION=FR
      - STRICT=1
    networks:
      - exercice4

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    env_file: ./docker/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - exercice4

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file: ./docker/pgadmin.env
    ports:
      - "5050:80"
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - exercice4

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    container_name: backend
    env_file: ./docker/backend.env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - tor  
    networks:
      - exercice4

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile
    container_name: frontend
    env_file: ./docker/frontend.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - exercice4

volumes:
  postgres_data:

networks:
  exercice4:
    driver: bridge