services:
  tor:
    image: dperson/torproxy
    container_name: tor
    restart: unless-stopped
    environment:
      - LOCATION=FR 
      - STRICT=1
      - TOR_MaxCircuitDirtiness=600 
    ports:
      - "9050:9050" 
      - "9051:9051" 
    networks:
      - exercice3

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - tor 
    networks:
      - exercice3
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - exercice3

networks:
  exercice3:
    driver: bridge